[package]
name = "proof_engine_zkboost_test"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
execution_layer = { workspace = true }
futures = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
reqwest = { workspace = true }
sensitive_url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
url = { workspace = true }
zkboost-server = { workspace = true }
zkboost-types = { workspace = true }
