[package]
name = "node_test_rig"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }

[dependencies]
beacon_node = { workspace = true }
beacon_node_fallback = { workspace = true }
bls = { workspace = true }
bytes = { workspace = true }
environment = { workspace = true }
eth2 = { workspace = true, features = ["events"] }
ethereum_ssz = { workspace = true }
ethereum_ssz_derive = { workspace = true }
execution_layer = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
sensitive_url = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ssz_types = { workspace = true }
task_executor = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tree_hash = { workspace = true }
types = { workspace = true }
validator_client = { workspace = true }
validator_dir = { workspace = true, features = ["insecure_keys"] }
validator_store = { workspace = true }
